/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
import * as vscode from 'vscode';

/** Localized labels shared with the isolated chat webview. */
export function getChatUiStrings(): Record<string, string> {
	return {
		includeSource: vscode.l10n.t('Include {0}'),
		estimatedTokens: vscode.l10n.t('estimated text tokens'),
		sourceExcluded: vscode.l10n.t('This source is excluded from the next message.'),
		queueMessage: vscode.l10n.t('Queue'),
		redirectMessage: vscode.l10n.t('Interrupt and Redirect'),
		queueCount: vscode.l10n.t('{0} Queued Follow-ups'),
		queuePaused: vscode.l10n.t('{0} Follow-ups · Paused'),
		pauseQueue: vscode.l10n.t('Pause Queue'),
		resumeQueue: vscode.l10n.t('Resume Queue'),
		moveEarlier: vscode.l10n.t('Move Earlier'),
		moveLater: vscode.l10n.t('Move Later'),
		editQueued: vscode.l10n.t('Edit'),
		removeQueued: vscode.l10n.t('Remove'),
		messageActions: vscode.l10n.t('Message Actions'),
		copyMessage: vscode.l10n.t('Copy Message'),
		branchHere: vscode.l10n.t('Branch Here'),
		helpful: vscode.l10n.t('Mark Response as Helpful'),
		notHelpful: vscode.l10n.t('Mark Response as Not Helpful'),
		reusePrompt: vscode.l10n.t('Reuse Prompt'),
		promptRestored: vscode.l10n.t('Prompt restored. Review context before sending; file and terminal attachments use their current contents.'),
		undoPromptRestore: vscode.l10n.t('Undo'),
		captureTerminalOutput: vscode.l10n.t('Capture Terminal Output'),
		terminalCaptureHelp: vscode.l10n.t('Attach output from the active terminal with the attachment menu or @terminal. Captures commands run after Anton starts, including output from running commands. Requires VS Code shell integration; keeps the latest lines within 16 KiB.'),
		terminalAttachmentHelp: vscode.l10n.t('Attach the latest command and output from the active terminal when you send. Requires shell integration.'),
		browseAcpAdapters: vscode.l10n.t('Browse ACP Adapters'),
		reviewWithCouncil: vscode.l10n.t('Review with Council'),
		councilHistory: vscode.l10n.t('Council History'),
		historyScope: vscode.l10n.t('Conversation Workspace'),
		allWorkspaces: vscode.l10n.t('All Workspaces'),
		thisWorkspace: vscode.l10n.t('This Workspace'),
		clearHistoryFilters: vscode.l10n.t('Clear Filters'),
		historyWorkspaceUnknown: vscode.l10n.t('Earlier conversation'),
		providerConfigured: vscode.l10n.t('Configured'),
		providerUnconfigured: vscode.l10n.t('Not configured'),
		managedByAcp: vscode.l10n.t('Managed by ACP'),
		acpModelHelp: vscode.l10n.t('Model selection is managed by the configured ACP agent: {0}'),
		integrations: vscode.l10n.t('Integrations'),
		integrationsHelp: vscode.l10n.t('Skills, plugins, and MCP servers discovered from Claude, Codex, Cursor, and shared agent folders. Skills load on demand. Connect MCP servers to make their tools available; source applications keep their own authentication and plugin UI.'),
		searchIntegrations: vscode.l10n.t('Search Integrations…'),
		integrationKind: vscode.l10n.t('Integration Type'),
		allIntegrations: vscode.l10n.t('All Types'),
		skills: vscode.l10n.t('Skills'),
		plugins: vscode.l10n.t('Plugins'),
		mcp: vscode.l10n.t('MCP Servers'),
		integrationLoading: vscode.l10n.t('Reading installed integrations…'),
		integrationWarnings: vscode.l10n.t('Configuration Warnings ({0})'),
		integrationRefresh: vscode.l10n.t('Refresh'),
		integrationResults: vscode.l10n.t('{0} integrations · {1} configuration warnings'),
		integrationEmpty: vscode.l10n.t('No integrations match this search.'),
		integrationConnect: vscode.l10n.t('Connect'),
		integrationDisconnect: vscode.l10n.t('Disconnect'),
		integrationOpen: vscode.l10n.t('Show Source'),
		integrationAvailable: vscode.l10n.t('Available'),
		integrationConfigured: vscode.l10n.t('Configured · Awaiting Connection'),
		integrationReady: vscode.l10n.t('Connected'),

		responseTable: vscode.l10n.t('Response Table'),
		usageUnavailable: vscode.l10n.t('Usage Unavailable'),
		externalUsage: vscode.l10n.t('Some routes do not report complete token usage or pricing. These totals are incomplete.'),
		responseStopped: vscode.l10n.t('Response Stopped'),
		searchConversations: vscode.l10n.t('Search Conversations…'),
		noConversations: vscode.l10n.t('No conversations match your search.'),
		showMore: vscode.l10n.t('Show More'),
		today: vscode.l10n.t('Today'),
		yesterday: vscode.l10n.t('Yesterday'),
		pastWeek: vscode.l10n.t('Previous 7 Days'),
		earlier: vscode.l10n.t('Earlier'),
		extensionVersion: vscode.l10n.t('Version: {0}'),
		conversationResult: vscode.l10n.t('{0} conversation'),
		conversationResults: vscode.l10n.t('{0} conversations'),
		workspaceContext: vscode.l10n.t('Workspace Context'),
		includeWorkspaceContext: vscode.l10n.t('Include Workspace Context'),
		contextExplanation: vscode.l10n.t('Inspect and exclude workspace context, attachments and mentions. A preview snapshot is reused for up to five minutes when its sources stay unchanged. Images travel separately; agent instructions, hooks and later tool results are managed by the runtime.'),
		refreshPreview: vscode.l10n.t('Refresh Preview'),
		contextExclusionsMigrated: vscode.l10n.t('Older context choices were restored with all mentioned sources excluded. Review Context before including any source.'),
		contextLoading: vscode.l10n.t('Reading workspace…'),
		contextEmpty: vscode.l10n.t('No automatic context available. Check the workspace context setting or open a source file.'),
		contextOff: vscode.l10n.t('Automatic context is off for this conversation.'),
		contextTokens: vscode.l10n.t('About {0} tokens'),
		chooseModel: vscode.l10n.t('Choose a Model'),
		searchModels: vscode.l10n.t('Search Models…'),
		noModels: vscode.l10n.t('No models match your search.'),
		modelUnavailable: vscode.l10n.t('This model is no longer in the provider catalog. Choose another model to send your message.'),
		draftSaved: vscode.l10n.t('Draft Saved'),
		draftImages: vscode.l10n.t('Text Draft Saved · Images Kept Until Reload'),
		newConversation: vscode.l10n.t('New Conversation'),
		on: vscode.l10n.t('On'),
		manageHistory: vscode.l10n.t('Manage History'),
		exportFeedback: vscode.l10n.t('Export Feedback'),
		historyView: vscode.l10n.t('History View'),
		activeHistory: vscode.l10n.t('Active'),
		archivedHistory: vscode.l10n.t('Archived'),
		trashHistory: vscode.l10n.t('Trash'),
		restoreConversation: vscode.l10n.t('Restore Conversation'),
		unpinConversation: vscode.l10n.t('Unpin Conversation'),
		pinConversation: vscode.l10n.t('Pin Conversation'),
		unarchiveConversation: vscode.l10n.t('Unarchive Conversation'),
		archiveConversation: vscode.l10n.t('Archive Conversation'),
		providerDiscovery: vscode.l10n.t('Providers and Coding Tools'),
		findProviders: vscode.l10n.t('Find Providers'),
		refreshProviders: vscode.l10n.t('Refresh Models'),
		serviceDiagnostics: vscode.l10n.t('Service Diagnostics'),
		discoveryLoading: vscode.l10n.t('Finding configured providers…'),
		integrationProfiles: vscode.l10n.t('Integration Profiles'),
		integrationChanges: vscode.l10n.t('Integration Changes'),
		checkUpdates: vscode.l10n.t('Check for Updates'),
		discoveryUpdated: vscode.l10n.t('Last Checked: {0}'),
		notChecked: vscode.l10n.t('Not Checked'),
		models: vscode.l10n.t('{0} Models'),
		credentials: vscode.l10n.t('Credentials: {0}'),
		inference: vscode.l10n.t('Inference: {0}'),
		catalogTruncated: vscode.l10n.t('Catalog truncated; refresh to retry.'),
		detectedCodingTools: vscode.l10n.t('Detected Coding Tools'),
		installed: vscode.l10n.t('Installed'),
		configurationFound: vscode.l10n.t('Configuration Found'),
		authFilePresent: vscode.l10n.t('Sign-in File Found'),
		authNotDetected: vscode.l10n.t('Sign-in Not Detected'),
		narrowModelSearch: vscode.l10n.t('Showing {0} of {1} models. Type to narrow your search.'),
		unknown: vscode.l10n.t('Unknown'),
		supported: vscode.l10n.t('Supported'),
		unsupported: vscode.l10n.t('Unsupported'),
		images: vscode.l10n.t('Images'),
		billing: vscode.l10n.t('Billing'),
		adapterContext: vscode.l10n.t('Context: {0} / {1}'),
		adapterReportedCost: vscode.l10n.t('Agent Reports: {0} {1}'),
		sessionResumed: vscode.l10n.t('Agent session resumed.'),
		sessionInterrupted: vscode.l10n.t('Previous session was interrupted. Starting a fresh session with conversation context.'),
		sessionTranscript: vscode.l10n.t('Starting a fresh agent session with conversation context.'),
		historyEarlier: vscode.l10n.t('Show Earlier Messages ({0})'),
		historyNewer: vscode.l10n.t('Show Newer Messages ({0})'),
		historyLatest: vscode.l10n.t('Jump to Latest Messages'),
		historyRange: vscode.l10n.t('Messages {0}–{1} of {2}'),
		historyLive: vscode.l10n.t('Current response stays visible while browsing history'),
		verifyProviderModel: vscode.l10n.t('Verify Model Tool Support'),
		off: vscode.l10n.t('Off'),
	};
}
